#:schema .vscode/air.schema.json

root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/app"
entrypoint = ["./tmp/main"]
include_ext = ["go", "env"]
exclude_dir = ["tmp", "vendor", "dist", "bin", "coverage"]
exclude_unchanged = true
log = "./tmp/build-errors.log"
delay = 300
stop_on_error = false
send_interrupt = true
kill_delay = 1000

[log]
time = true
main_only = false
silent = false

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = true
keep_scroll = true
